### ISSUE TITLE
signIn fails because of unexpected JSON token `NewDeviceMetadata`

### ISSUE THREAD

**Issue by AndreasBoehm** [Liftric/cognito-idp#49]
The AuthenticationResult response can return a field `NewDeviceMetadata`  when device tracking was activated in cognito.
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html

Please add support for `NewDeviceMetadata` or allow us to use `ignoreUnknownKeys = true`

The library throws an exception when i do so.
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2134: Encountered an unknown key 'NewDeviceMetadata'.
    Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
    JSON input: .....RkoGKIeVO5tvkseJtxKyC26YtaQ","NewDeviceMetadata":{"DeviceGro.....
        at app//kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at app//kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at app//kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:514)
        at app//kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:510)
        at app//kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:152)
        at app//kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:140)
        at app//kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:79)
        at app//com.liftric.cognito.idp.core.AuthenticationResult$$serializer.deserialize(Response.kt:21)
        at app//com.liftric.cognito.idp.core.AuthenticationResult$$serializer.deserialize(Response.kt:21)
        at app//kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at app//kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
        at app//kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at app//kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at app//com.liftric.cognito.idp.core.SignInResponse$$serializer.deserialize(Response.kt:15)
        at app//com.liftric.cognito.idp.core.SignInResponse$$serializer.deserialize(Response.kt:15)
        at app//kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at app//kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
        at app//kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
        at app//com.liftric.cognito.idp.IdentityProviderClient.signIn$suspendImpl(IdentityProviderClient.kt:524)
        at app//com.liftric.cognito.idp.IdentityProviderClient$signIn$1.invokeSuspend(IdentityProviderClient.kt)
```

If you need more information, please let me know.

**Comment by gaebel** [comment]
Hi @AndreasBoehm, I'll create a patch release in a bit with `NewDeviceMetadata`, and `ignoreUnknownKeys` enabled to avoid such issues in the future.
